services:
    frontend:
        build:
            context: .
            dockerfile: ./frontend.Dockerfile
        command: npm run dev # /bin/sh
        ports:
            - '3000:3000' # Serve the React app on port 3000
        volumes:
            - ./:/usr/src/app/
        #     - ./frontend:/usr/src/app/frontend # Sync local frontend code for hot reloading
    #         # - /usr/src/app/node_modules # Prevent overwriting of node_modules
    #     stdin_open: true
    #     tty: true
    app:
        build: .
        command: python /usr/src/app/manage.py runserver 0.0.0.0:8000
        volumes:
            - ./:/usr/src/app/
            # - frontend-build:/usr/src/app/static/
        ports:
            - '8000:8000'
        stdin_open: true # docker run -i
        tty: true # docker run -t
volumes:
    frontend-build:
